### ISSUE TITLE
no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by lszlfrng** [tacid/redmine_print_issue#1]
Dear Developer,
we start to use your plugin but when I open the config I got error. What is wrong in our system?
Best regards,
Laszlo Firnaga

Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_print_issue"}
  Current user: laszlo.firnaga (id=3)
  Rendered plugins/redmine_print_issue/app/views/settings/_redmine_print_issue_settings.erb (3.2ms)
  Rendered settings/plugin.html.erb within layouts/admin (121.7ms)
Completed 500 Internal Server Error in 294ms (ActiveRecord: 13.3ms)

ActionView::Template::Error (no implicit conversion of String into Integer):
    1: <% if settings[:print_templates].count == 1 and settings[:print_templates]["Default"].blank? then
    2:      settings[:print_templates]["Default"] = render(partial: 'issues/print_example_template')
    3: end %>
    4: <% content_for :header_tags do %>
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb__3973684270015884410_43624660'
  app/views/settings/plugin.html.erb:4:in`_app_views_settings_plugin_html_erb__3973684270015884410_43624660'

Our Redmine environment is:
  Redmine version                3.0.3.stable
  Ruby version                   2.0.0-p598 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               PostgreSQL

**Comment by tacid** [comment]
I'm now rewriting plugin to work with multiple templates and to use ODT 
templates, so this is my current goal, so this version on github is 
currently broken. I think you can rollback some commits back and there 
will be working version

**Comment by lszlfrng** [comment]
Thank you Paul!
1. nov. 30. dátummal, 15:01 időpontban Paul notifications@github.com írta:

**Comment by tacid** [comment]
For now you can just use the last 1.0.2 version it is know as working ok
https://github.com/tacid/redmine_print_issue/releases/tag/v1.0.3
